# The deployment section should be excluded until
# it is explicitly included in module 5

#deployment:
#  dockerhub:
#    branch: master
#    commands:
#      - $DOCKER_HUB_TRIGGER

#test:
#  override:    
#    - mocha

version: 2.1 # use CircleCI 2.0
executors:
  docker-publisher:
    environment:
      IMAGE_NAME: magedelmalah/training-docker-ci
      DOCKERHUB_USERNAME: magedelmalah
      DOCKERHUB_PASS: auto@123
    docker:
      - image: circleci/node:latest
jobs: # a collection of steps
  build: # runs not using Workflows must have a `build` job as entry point
    executor: docker-publisher
    environment:
      IMAGE_NAME: magedelmalah/training-docker-ci
      DOCKERHUB_USERNAME: magedelmalah
      DOCKERHUB_PASS: auto@123
    working_directory: ~/src # directory where steps will run
    steps: # a collection of executable commands
      - checkout

      # Update npm
      - run:
          name: update-npm
          command: 'sudo npm install -g npm@latest'

      # Download and cache dependencies
      - restore_cache:
          keys:
              - v1-dependencies-{{ checksum "package.json" }}
              # fallback to using the latest cache if no exact match is found
              - v1-dependencies-

      - run: npm install

      - run: npm install mocha-junit-reporter # just for CircleCI

      - save_cache:
          paths:
              - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      - run: mkdir reports
      # Run mocha
      - run: npm test
      
      - setup_remote_docker
      - run:
          name: Build Docker image
          command: docker build -t $IMAGE_NAME:latest .
      - run:
          name: Archive Docker image
          command: docker save -o image.tar $IMAGE_NAME
      - persist_to_workspace:
          root: .
          paths:
            - ./image.tar
          
  publish-latest:
    executor: docker-publisher
    steps:
      - attach_workspace:
          at: /tmp/workspace
      - setup_remote_docker
      - run:
          name: Load archived Docker image
          command: docker load -i /tmp/workspace/image.tar
      - run:
          name: Publish Docker Image to Docker Hub
          command: |
            echo "$DOCKERHUB_PASS" | docker login -u "$DOCKERHUB_USERNAME" --password-stdin
            docker push $IMAGE_NAME:latest

workflows:
  version: 2
  build-master:
    jobs:
      - build:
        filters:
          branches:
            only: master
            
      - publish-latest:
          requires:
            - build
          filters:
            branches:
              only: master